### ISSUE TITLE
compatible mon pilotage elec

### ISSUE THREAD

**Issue by phid78** [Maxou44/ha-tiko-component#1]
Bonjour, 
Est il possible que tu le rende compatible avec mon pilotage elec ?
Bonne journée

**Comment by Maxou44** [comment]
Bonjour,

Je n'ai pas de compte "mon pilotage elec" pour pouvoir tester et gérer la compatibilité, pourriez vous me partager votre compte, que je fasse des tests et que j'adapte le code en conséquence pour gérer les deux ?

Je vous laisse mon email si vous accepter de me partager votre compte : m.baconnais@outlook.com

Bonne journée,
Maxime

**Comment by Maxou44** [comment]
Hello @phid78,

Je viens de mettre à jour le module pour ajouter le support de Tiko.ch, n'hésites pas à me faire des retours une fois que tu as testé, les capteurs d'humidité et de batterie ont été retirés si il n'y en a pas 🙂

![tiko ch support](https://github.com/user-attachments/assets/f86fbf71-9ee6-4936-b9d9-aba3aa5f6656)
